version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    container_name: idp-backend
    ports:
      - "5002:5002"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://idp:idp123@postgres:5432/idpdb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - idp-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: idp-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - idp-net


  postgres:
    image: postgres:15
    container_name: idp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: idp123
      POSTGRES_DB: idpdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - idp-net

  nginx:
    image: nginx:latest
    container_name: idp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - idp-net

volumes:
  pgdata:

networks:
  idp-net:
    driver: bridge
